spring:
  application:
    name: user
  http:
    encoding:
      charset: utf-8
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 60001