spring:
  application:
    name: es
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 10102
logging:
  level: info
