spring:
  application:
    name: es
  profiles:
    active: dev
#  data:
#    elasticsearch:
#      cluster-name: my-application
#      cluster-nodes: localhost:9300
#      repositories:
#        enabled: true
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 10102
logging:
  level: debug