spring:
  application:
    name: es
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
#  data:
#    elasticsearch:
#      cluster-name: my-application
#      cluster-nodes: localhost:9300
#      repositories:
#        enabled: true
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 5
server:
  port: 10102
info:
  app:
    name: "ElasticSearch Server Node"
    description: "This is a ElasticSearch Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"