server:
  port: 37332
spring:
  application:
    name: admin
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization: true
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
info:
  version: 1.0