server:
  port: 10001
eureka:
  instance:
    hostname: localhost
  server:
      enableSelfPreservation: false
      eviction-interval-timer-in-ms: 60000
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultzone: ${eureka.instance.hostname}:${server.port}/eureka/
