spring:
  application:
    name: eureka
server:
  port: 10001
eureka:
  instance:
    hostname: localhost
  server:
      enableSelfPreservation: false
      eviction-interval-timer-in-ms: 60000
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultzone: ${eureka.instance.hostname}:${server.port}/eureka/
info:
  app:
    name: "Eureka Server Node"
    description: "This is a Eureka Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"