spring:
  application:
    name: core
  data:
    mongodb:
      host: localhost
      port: 27017
      database: op
      repositories:
        enabled: true
server:
  port: 10129
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10