spring:
  application:
    name: core
  data:
    mongodb:
      host: localhost
      port: 27017
      database: op
      repositories:
        enabled: true
server:
  port: 20001
  connection-timeout: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.235:8761/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10