spring:
  application:
    name: core
  data:
    mongodb:
      host: localhost
      port: 27017
      database: op
      repositories:
        enabled: true
  profiles:
      active: dev
  http:
      encoding:
        charset: utf-8
        force: true
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 20001
  connection-timeout: 60000