spring:
  application:
    name: core
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/op
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 10120