spring:
  application:
    name: metris
server:
  port: 11234
info:
  app:
    name: "Metric Server Node"
    description: "This is a Message Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"