package com.op.oauth.mybatis;

import com.op.oauth.mybatis.OauthApprovals;
import com.op.oauth.mybatis.OauthApprovalsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthApprovalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int countByExample(OauthApprovalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int deleteByExample(OauthApprovalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insert(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insertSelective(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthApprovals> selectByExample(OauthApprovalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExample(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsExample example);
}