package com.op.oauth.mybatis;

import com.op.oauth.mybatis.OauthCode;
import com.op.oauth.mybatis.OauthCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int countByExample(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int deleteByExample(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insert(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insertSelective(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthCode> selectByExampleWithBLOBs(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthCode> selectByExample(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthCode record, @Param("example") OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OauthCode record, @Param("example") OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExample(@Param("record") OauthCode record, @Param("example") OauthCodeExample example);
}