package com.op.oauth.mybatis;

import java.util.Date;

public class OauthApprovals {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.userId
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.clientId
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.scope
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.status
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.expiresAt
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private Date expiresat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.lastModifiedAt
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private Date lastmodifiedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.userId
     *
     * @return the value of oauth_approvals.userId
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.userId
     *
     * @param userid the value for oauth_approvals.userId
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.clientId
     *
     * @return the value of oauth_approvals.clientId
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.clientId
     *
     * @param clientid the value for oauth_approvals.clientId
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.scope
     *
     * @return the value of oauth_approvals.scope
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.scope
     *
     * @param scope the value for oauth_approvals.scope
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.status
     *
     * @return the value of oauth_approvals.status
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.status
     *
     * @param status the value for oauth_approvals.status
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.expiresAt
     *
     * @return the value of oauth_approvals.expiresAt
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public Date getExpiresat() {
        return expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.expiresAt
     *
     * @param expiresat the value for oauth_approvals.expiresAt
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setExpiresat(Date expiresat) {
        this.expiresat = expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.lastModifiedAt
     *
     * @return the value of oauth_approvals.lastModifiedAt
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public Date getLastmodifiedat() {
        return lastmodifiedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.lastModifiedAt
     *
     * @param lastmodifiedat the value for oauth_approvals.lastModifiedAt
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setLastmodifiedat(Date lastmodifiedat) {
        this.lastmodifiedat = lastmodifiedat;
    }
}