package com.op.oauth.mybatis;

public class OauthRefreshToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.token_id
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    private byte[] token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.authentication
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    private byte[] authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.token_id
     *
     * @return the value of oauth_refresh_token.token_id
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.token_id
     *
     * @param tokenId the value for oauth_refresh_token.token_id
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.token
     *
     * @return the value of oauth_refresh_token.token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.token
     *
     * @param token the value for oauth_refresh_token.token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    public void setToken(byte[] token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.authentication
     *
     * @return the value of oauth_refresh_token.authentication
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.authentication
     *
     * @param authentication the value for oauth_refresh_token.authentication
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }
}