package com.op.oauth.mybatis;

import com.op.oauth.mybatis.OauthAccessToken;
import com.op.oauth.mybatis.OauthAccessTokenExample;
import com.op.oauth.mybatis.OauthAccessTokenWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int countByExample(OauthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int deleteByExample(OauthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insert(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insertSelective(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthAccessTokenWithBLOBs> selectByExampleWithBLOBs(OauthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthAccessToken> selectByExample(OauthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthAccessTokenWithBLOBs record, @Param("example") OauthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OauthAccessTokenWithBLOBs record, @Param("example") OauthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExample(@Param("record") OauthAccessToken record, @Param("example") OauthAccessTokenExample example);
}