package com.op.oauth.mybatis;

import com.op.oauth.mybatis.OauthClientToken;
import com.op.oauth.mybatis.OauthClientTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthClientTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int countByExample(OauthClientTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int deleteByExample(OauthClientTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insert(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int insertSelective(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthClientToken> selectByExampleWithBLOBs(OauthClientTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    List<OauthClientToken> selectByExample(OauthClientTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    int updateByExample(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenExample example);
}