package com.op.oauth.mybatis;

import com.op.oauth.mybatis.OauthRefreshToken;
import com.op.oauth.mybatis.OauthRefreshTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthRefreshTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int countByExample(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int deleteByExample(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int insert(OauthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int insertSelective(OauthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    List<OauthRefreshToken> selectByExampleWithBLOBs(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    List<OauthRefreshToken> selectByExample(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthRefreshToken record, @Param("example") OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OauthRefreshToken record, @Param("example") OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated Tue Feb 28 17:49:19 CST 2017
     */
    int updateByExample(@Param("record") OauthRefreshToken record, @Param("example") OauthRefreshTokenExample example);
}