package com.op.oauth.mybatis;

public class OauthCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_code.code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_code.authentication
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    private byte[] authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_code.code
     *
     * @return the value of oauth_code.code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_code.code
     *
     * @param code the value for oauth_code.code
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_code.authentication
     *
     * @return the value of oauth_code.authentication
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_code.authentication
     *
     * @param authentication the value for oauth_code.authentication
     *
     * @mbggenerated Tue Feb 28 17:49:18 CST 2017
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }
}