spring:
  application:
    name: message
  rabbitmq:
    host: localhost
    port: 5672
    username: xuning
    password: xuning!
    listener:
      prefetch: 1
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 5
server:
  port: 40001
info:
  app:
    name: "Message Server Node"
    description: "This is a Message Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"