spring:
  application:
    name: analysis
  profiles:
      active: dev
  output:
    ansi:
      enabled: always
  http:
      encoding:
        charset: utf-8
        force: true
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 5
server:
  port: 34334
  connection-timeout: 60000
info:
  app:
    name: "Analysis Server Node"
    description: "This is a Analysis Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"