server:
  port: 10011
  connection-timeout: 60000
spring:
  application:
    name: proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 30
zuul:
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauth
    msg:
      path: /msg/**
      serviceId: message