server:
  port: 10011
spring:
  application:
    name: cloud-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10