server:
  port: 8080
  connection-timeout: 6000
spring:
  application:
    name: proxy
  http:
    encoding:
      charset: utf-8
      force: true
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 5
zuul:
  routes:
    oauth:
      path: /oauth/api/**
      serviceId: oauth
    msg:
      path: /msg/api/**
      serviceId: message
    es:
      path: /es/api/**
      serviceId: es
    user:
      path: /user/api/**
      serviceId: user
    core:
      path: /core/api/**
      serviceId: core
    customer:
      path: /customer/api/**
      serviceId: customer
    analysis:
      path: /analysis/api/**
      serviceId: analysis
  host:
    connect-timeout-millis: 1000
    socket-timeout-millis: 6000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 6000
info:
  app:
    name: "Proxy Server Node"
    description: "This is a Proxy Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"