server:
  port: 8080
  connection-timeout: 600000
spring:
  application:
    name: proxy
  http:
    encoding:
      charset: utf-8
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 30
zuul:
  routes:
    oauth:
      path: /oauth/api/**
      serviceId: oauth
    msg:
      path: /msg/api/**
      serviceId: message
    es:
      path: /es/api/**
      serviceId: es
    user:
      path: /user/api/**
      serviceId: user
    core:
      path: /core/api/**
      serviceId: core
    customer:
      path: /customer/api/**
      serviceId: customer
    analysis:
      path: /analysis/api/**
      serviceId: analysis