server:
  port: 8080
  connection-timeout: 600000
spring:
  application:
    name: proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 30
zuul:
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauth
    msg:
      path: /msg/**
      serviceId: message
    es:
      path: /es/**
      serviceId: es
    user:
      path: /user/**
      serviceId: user
    core:
      path: /core/**
      serviceId: core
    customer:
      path: /customer/**
      serviceId: customer