spring:
  application:
    name: oauth
  output:
    ansi:
      enabled: always
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/op?useUnicode=true&characterEncoding=utf8
    username: root
    password: xnjm0611
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          idle-timeout: 10000
          maximum-pool-size: 10
          pool-name: hikari-pool
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml
  typeAliasesPackage: com.op.oauth.bean.entity
eureka:
  server:
    url: http://localhost:10001/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.server.url}
  instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 5
server:
  port: 30001
  connection-timeout: 60000
info:
  app:
    name: "Oauth Server Node"
    description: "This is a Oauth Server Node"
    version: "v1.0"
    spring-boot-version: "1.4.2"
    status: "success"