spring:
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/op?characterEncoding=utf8
    username: root
    password: xnjm0611
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  profiles:
    active: dev

mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml
  typeAliasesPackage: com.op.oauth.bean.entity