spring:
  application:
    name: oauth
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/op?useUnicode=true&characterEncoding=utf8
    username: root
    password: xnjm0611
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          idle-timeout: 10000
          maximum-pool-size: 10
          pool-name: hikari-pool
  profiles:
    active: dev
mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml
  typeAliasesPackage: com.op.oauth.bean.entity
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 30001
  connection-timeout: 600000